### ISSUE TITLE
⊗ operator in eq (4)

### ISSUE THREAD

**Issue by frpnz** [ykwon0407/UQ_BNN#11]
Dear author, 
thank you for your exciting work.
I cannot understand the meaning and the function of the operator ⊗ in eq (4) of your paper https://openreview.net/pdf?id=Sk_P2Q9sG&source=post_page
Could you please clarify it for me?
Thanks

Francesco

**Comment by ykwon0407** [comment]
Hi Francesco! As described below the Equation (2), `v ⊗2` means that `v v^T`. So, if you have a `d`-dimensional vector, then `d ⊗2` will be a `d by d` matrix whose (i,j)-th element is `v_j * v_j`.
