### ISSUE TITLE
another question about p_hat

### ISSUE THREAD

**Issue by ShellingFord221** [ykwon0407/UQ_BNN#5]
Why do you only use [0] of prediction results in line 63, /retina/utils.py? Shouldn't p_hat be made up of the probabilities of all classes?

**Comment by ShellingFord221** [comment]
In your paper, the explanation of p_hat under Eq. 4 is: p_hat = Softmax{f(x*)}, therefore I think that p_hat should be made up of the probabilities of all classes after softmax layer.

**Comment by ykwon0407** [comment]
@ShellingFord221  Hello~ 
Why do you only use [0] of prediction results in line 63, /retina/utils.py? Shouldn't p_hat be made up of the probabilities of all classes?
In your paper, the explanation of p_hat under Eq. 4 is: p_hat = Softmax{f(x*)}, therefore I think that p_hat should be made up of the probabilities of all classes after softmax layer.
-> You are right. However, in this GitHub codes, the similar concept applied to another [issue](https://github.com/ykwon0407/UQ_BNN/issues/4#issuecomment-454999124) you wrote goes again, indexing [0] is enough to obtain the ```p_hat```.
Please note that knowing P(y=1) is sufficient to know ```p_hat``` in case of binary classification.

Hope this information helps you!

**Comment by ShellingFord221** [comment]
Hi,
    I suddenly realize that p_hat is just for ONE test data according to the explanation under Eq. 4: p_hat = Softmax{f(x*)}, where x* means a new input. Can I rewrite Eq. 4 to get aleatoric and epistemic uncertainty of ALL test data (e.g. 10000 samples)? Because I think the uncertainty metrics are more appropriate in the case of all test data, aleatoric and epistemic uncertainty should mean the uncertainty about the whole test set.

**Comment by ykwon0407** [comment]
Not really. It is because, in general, the 'uncertainty' is terminology for one random variable X*. Once you have averaged the uncertainties using whole test data, then it would estimate Var(y*), not Var(y* | x*).

If you want to see overall _uncertainty_, then I guess you can compute by averaging all terms. It depends on what quantity you want.
