### ISSUE TITLE
about y*

### ISSUE THREAD

**Issue by ShellingFord221** [ykwon0407/UQ_BNN#8]
Hi, in your appendix,
![image](https://user-images.githubusercontent.com/40685673/60518130-7981cd00-9d13-11e9-8957-cb1875b72d43.png)
Why is y* one-hot encoded? Should y* be the probabilities of all classes? (e.g., there are 3 classes, then y* may be [0.1, 0.6, 0.3])

If it is a label, how to get it by average T times samples?
![image](https://user-images.githubusercontent.com/40685673/60519751-c2875080-9d16-11e9-83a3-7601434bd76e.png)

Thanks

**Comment by ykwon0407** [comment]
Sorry for the late reply. 

1.
y^* should be considered as a multinomial random variable with size n=1 and mean P(y^* | x^*, \omega). And the multinomial random variable y^* can be represented as a one-hot encoded value.

In your example, [0.1, 0.6, 0.3] is something like mean P(y^* | x^*, \omega) and it means 

y^*=1 with probability 0.1
y^*=2 with probability 0.6
y^*=3 with probability 0.3

2.
After T random draws, we calculate p(y^* | x^*, \hat{\omega}_t), not one-hot encoded value.

Reference
- Multinomial distribution: https://en.wikipedia.org/wiki/Multinomial_distribution
