### ISSUE TITLE
Deriving the decomposition into aleatoric and epistemic uncertainty

### ISSUE THREAD

**Issue by btlorch** [ykwon0407/UQ_BNN#9]
Dear Mr. Kwon,

we enjoyed reading your papers on decomposing predictive variance into aleatoric and epistemic uncertainty in classification settings without the need of an extra output layer. Thank you also for sharing your code online.

After reading your derivation to decomposing the predictive variance as given in Appendix A in your paper "Uncertainty quantification using Bayesian neural networks in classification: Application to biomedical image segmentation", we had difficulties to understand the step from the second to last line to the next. I'm pasting the the two lines over here:

![decomposition](https://user-images.githubusercontent.com/11959715/79503003-bfa0e680-8030-11ea-82b7-f53dd39f72de.png)

Can you please clarify why the outer product (denoted as $\otimes 2$) can be moved outside of the difference? I think sum and outer products cannot be interchanged as demonstrated by the example below, but I might be missing some trick or assumption here.

![outer_product_example](https://user-images.githubusercontent.com/11959715/79503005-c0397d00-8030-11ea-9368-89c2c8b43312.png)

Thank you for your help!

**Comment by ykwon0407** [comment]
Hello @btlorch. Thank you for your interest in our paper. 
There are no flaws in your derivation and the last equation is obtained via the integration. Below I elaborate on this. 

Let $a = \mathbb{E}_{p(y^* | x^*, \omega)}(y^*)$ and $b = \mathbb{E}_{p(y^* | x^*,  \mathcal{D} )}(y^*)$. Then, 
$[a-b]^{\otimes 2} = aa^{T} +bb^{T}  -ab^{T}  -ba^{T}$ and $\int a p(\omega | \mathcal{D}) d \omega = b$ give
$\int [a-b]^{\otimes 2} p(\omega | \mathcal{D}) d \omega = \int aa^{T} p(\omega | \mathcal{D}) d \omega  +bb^{T}  -bb^{T}  -bb^{T} = \int aa^{T} -bb^{T} p(\omega | \mathcal{D}) d \omega$. (Please note that $b$ is constant with respect to $p(\omega | \mathcal{D})$. I hope this helps you.

**Comment by btlorch** [comment]
Thanks a lot for clarifying!
